//ACTIVITY: Write a program that takes input from user and compares to computer generated number 


//Random Number generated by computer
var randomnumber=Math.floor((Math.random()*10)+1);
//Take input from user
guess:
var usernumber = prompt("Enter a number between 1 to 10");
//check condition
if(usernumber==randomnumber){
    alert("Congrats! you won!");
}
else if(usernumber>randomnumber){
alert( `The number guessed (${usernumber}) is greater than Computer generated number(${randomnumber}). Better luck next time`);
}
else if(usernumber<randomnumber){
    alert(`The number guessed (${usernumber}) is lesser than Computer generated number (${randomnumber}). Better luck next time`);
}
else{
    document.write("Invalid input")
}
